-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.patient
(
    uuid character(16) COLLATE pg_catalog."default" NOT NULL,
    full_name character(50) COLLATE pg_catalog."default" NOT NULL,
    gender character(10) COLLATE pg_catalog."default" NOT NULL,
    birthdate character(20) COLLATE pg_catalog."default" NOT NULL,
    nationality character(30) COLLATE pg_catalog."default" NOT NULL,
    uuid_relation character(16) COLLATE pg_catalog."default",
    CONSTRAINT patient_pkey PRIMARY KEY (uuid)
);
END;